apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  source:
    path: app-of-apps
    helm:
      parameters:
        - name: "argocd.giropopsSenhas.enabled"
          value: "false"
        - name: "argocd.randomLogger.enabled"
          value: "false"
    repoURL: https://github.com/alextreviso/gitops-argocd
    targetRevision: feat/day2
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
