apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  source:
    helm: {}
    path: giropops-senhas/helm
    repoURL: https://github.com/alextreviso/gitops-argocd
    targetRevision: feat/day2
  destination:
    namespace: giropops-senhas
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
