apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-logger
  namespace: argocd
spec:
  source:
    helm: {}
    path: random-logger
    repoURL: https://github.com/alextreviso/gitops-argocd
    targetRevision: feat/day2
  destination:
    namespace: random-logger
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
