apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/alextreviso/gitops-argocd
      revision: feat/day3
      directories:
      - path: applicationset/apps/*/helm
      - path: applicationset/apps/random-logger/helm
        # exclude: true
  template:
    metadata:
      name: '{{index .path.segments 3}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/alextreviso/gitops-argocd
        targetRevision: feat/day3
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true